mysql:
    host:     localhost
    username: lemon_db
    password: 2b21789cd0f4747a7604999c0b69fd0d
    dbname:   lemon_db

log:
    enable: true
    path:   /var/log/lemon/

bookmakers:
    Bwin:
        base: http://sports.bwin.es/
        odds:
            three:
                Football: es/sports/4/apuestas/f%c3%batbol
            two:
                Basket: es/sports/7/apuestas/baloncesto
                Tennis: es/sports/5/apuestas/tenis
    Betfair:
        base: http://sports.betfair.es/
        odds:
            three:
                Football: football
            two:
                Basket: basketball
                Tennis: tennis
    Pinnacle:
        base: http://xml.pinnaclesports.com/pinnacleFeed.aspx?sportType=
        odds:
            three:
                Football: Soccer
            two:
                Basket: Basketball
                Tennis: Tennis
