<?php

/**
 * Expert
 *
 * This class is the bets expert, hence it will provide decisions on
 * where should we bet based on the input generated by the Parser.
 *
 * @author Sava Gerov <sava@gerov.es>
 */

namespace Lemon;

class Expert
{

}
